//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int cID { get; set; }
        public string cName { get; set; }
        public string cPass { get; set; }
        public Nullable<int> cUser { get; set; }
        public string cAd { get; set; }
        public string NamePhoto { get; set; }
    }
}
